- ignore: {name: "Use newtype instead of data"}
- ignore: {name: "Avoid lambda"}
- ignore: {name: "Redundant lambda"}
- ignore: {name: "Use >>"}
- ignore: {name: "Use const"}
- ignore: {name: "Redundant return"}
- ignore: {name: "Use tuple-section"}
- ignore: {name: "Use mapM_"}
